import type { TemplateSchema } from '@/types';

export const energySourceSchema: TemplateSchema = {
  id: 'energy-source',
  name: 'Energy - Sources',
  description: 'Energy generation and sales sources tracked for renewable energy reporting.',
  group: 'Energy',
  icon: 'Zap',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'energy id', 'energy source id', 'code'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the energy source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'energy source name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the energy source',
    },
    {
      name: 'Type',
      aliases: ['energy type', 'source type', 'generation type'],
      type: 'enum',
      required: true,
      description: 'Whether energy is generated or sold',
      allowedValues: ['Generated', 'Sold'],
    },
    {
      name: 'Energy Source',
      aliases: ['source', 'fuel', 'fuel type', 'energy fuel', 'generation source'],
      type: 'enum',
      required: true,
      description: 'Type of energy source',
      allowedValues: [
        'Biodiesel', 'Other biofuels', 'Geothermal', 'Hydroelectric', 'Solar', 'Wind', 'Nuclear',
        'Non-Renewable Electricity', 'Diesel', 'LPG', 'Automotive LPG', 'Natural Gas',
        'Bituminous Coal', 'Sub-bituminous coal', 'Anthracite', 'Brown coal (lignite)',
        'Coking coal', 'Coal briquettes', 'Coal tar',
      ],
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id', 'facility'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date', 'effective date'],
      type: 'date',
      required: true,
      description: 'Date the energy source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date', 'decommission date'],
      type: 'date',
      required: false,
      description: 'Date the energy source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const energyQtySchema: TemplateSchema = {
  id: 'energy-qty',
  name: 'Energy - Quantities',
  description: 'Energy generation and sales quantity data for reporting periods.',
  group: 'Energy',
  icon: 'Zap',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'energy source id', 'source identifier'],
      type: 'text',
      required: true,
      description: 'Identifier of the energy source',
    },
    {
      name: 'Energy Generated (optional)',
      aliases: ['generated', 'generation', 'energy generated', 'kwh generated', 'generated qty'],
      type: 'number',
      required: false,
      description: 'Amount of energy generated',
    },
    {
      name: 'Energy Sold (optional)',
      aliases: ['sold', 'energy sold', 'kwh sold', 'sold qty'],
      type: 'number',
      required: false,
      description: 'Amount of energy sold',
    },
    {
      name: 'Unit',
      aliases: ['unit', 'uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (e.g. kWh, MWh, GJ)',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date'],
      type: 'date',
      required: true,
      description: 'Start of the reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end', 'end date'],
      type: 'date',
      required: false,
      description: 'End of the reporting period',
    },
  ],
  uniqueConstraint: ['Identifier'],
};
