import type { TemplateSchema } from '@/types';

export const habitatBiodiversitySourceSchema: TemplateSchema = {
  id: 'habitat-biodiversity-source',
  name: 'Habitat & Biodiversity - Sources',
  description: 'Habitat and biodiversity monitoring sources for environmental reporting.',
  group: 'Habitat & Biodiversity',
  icon: 'TreePine',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'habitat id'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the habitat/biodiversity source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the source',
    },
    {
      name: 'Type',
      aliases: ['type', 'source type', 'habitat type', 'monitoring type'],
      type: 'enum',
      required: true,
      description: 'Type of habitat/biodiversity monitoring',
      allowedValues: ['Wildlife fatalities', 'Habitat management', 'Species endangerment assessment'],
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date'],
      type: 'date',
      required: true,
      description: 'Date the source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date'],
      type: 'date',
      required: false,
      description: 'Date the source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const habitatManagementQtySchema: TemplateSchema = {
  id: 'habitat-management-qty',
  name: 'Habitat Management - Quantities',
  description: 'Habitat management area data including removal, restoration and protection metrics.',
  group: 'Habitat & Biodiversity',
  icon: 'TreePine',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'habitat id'],
      type: 'text',
      required: true,
      description: 'Identifier of the habitat source',
    },
    {
      name: 'Date',
      aliases: ['date', 'reporting date', 'assessment date', 'period'],
      type: 'date',
      required: true,
      description: 'Date of the habitat assessment',
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'area unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (e.g. hectares, sq km)',
    },
    {
      name: 'Habitat Removed',
      aliases: ['removed', 'area removed', 'habitat cleared', 'cleared'],
      type: 'number',
      required: false,
      description: 'Area of habitat removed',
    },
    {
      name: 'Habitat Enhanced/Restored',
      aliases: ['enhanced', 'restored', 'area restored', 'rehabilitation'],
      type: 'number',
      required: false,
      description: 'Area of habitat enhanced or restored',
    },
    {
      name: 'Habitat Protected (On-site)',
      aliases: ['protected onsite', 'on-site protected', 'onsite protection'],
      type: 'number',
      required: false,
      description: 'Area of habitat protected on-site',
    },
    {
      name: 'Habitat Protected (Off-site)',
      aliases: ['protected offsite', 'off-site protected', 'offsite protection'],
      type: 'number',
      required: false,
      description: 'Area of habitat protected off-site',
    },
    {
      name: 'Habitat Maintained',
      aliases: ['maintained', 'area maintained', 'maintenance'],
      type: 'number',
      required: false,
      description: 'Area of habitat maintained',
    },
  ],
};

export const speciesEndangermentQtySchema: TemplateSchema = {
  id: 'species-endangerment-qty',
  name: 'Species Endangerment - Quantities',
  description: 'Species endangerment assessment counts by IUCN Red List category.',
  group: 'Habitat & Biodiversity',
  icon: 'TreePine',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'assessment id'],
      type: 'text',
      required: true,
      description: 'Identifier of the assessment source',
    },
    {
      name: 'Date',
      aliases: ['date', 'assessment date', 'reporting date', 'period'],
      type: 'date',
      required: true,
      description: 'Date of the species assessment',
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Critically Endangered',
      aliases: ['critically endangered', 'cr', 'critical'],
      type: 'number',
      required: false,
      description: 'Number of critically endangered species',
    },
    {
      name: 'Endangered',
      aliases: ['endangered', 'en'],
      type: 'number',
      required: false,
      description: 'Number of endangered species',
    },
    {
      name: 'Vulnerable',
      aliases: ['vulnerable', 'vu'],
      type: 'number',
      required: false,
      description: 'Number of vulnerable species',
    },
    {
      name: 'Near Threatened',
      aliases: ['near threatened', 'nt'],
      type: 'number',
      required: false,
      description: 'Number of near threatened species',
    },
    {
      name: 'Least Concern',
      aliases: ['least concern', 'lc'],
      type: 'number',
      required: false,
      description: 'Number of least concern species',
    },
  ],
};

export const wildlifeFatalitiesQtySchema: TemplateSchema = {
  id: 'wildlife-fatalities-qty',
  name: 'Wildlife Fatalities - Quantities',
  description: 'Wildlife fatality counts for threatened and non-threatened species.',
  group: 'Habitat & Biodiversity',
  icon: 'TreePine',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'fatality id'],
      type: 'text',
      required: true,
      description: 'Identifier of the fatality source',
    },
    {
      name: 'Date',
      aliases: ['date', 'incident date', 'reporting date', 'period'],
      type: 'date',
      required: true,
      description: 'Date of the fatality record',
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Non-threatened Fatalities',
      aliases: ['non-threatened', 'non threatened', 'other fatalities'],
      type: 'number',
      required: false,
      description: 'Number of non-threatened species fatalities',
    },
    {
      name: 'Threatened Fatalities',
      aliases: ['threatened', 'threatened species', 'endangered fatalities'],
      type: 'number',
      required: false,
      description: 'Number of threatened species fatalities',
    },
  ],
};
