import type { TemplateSchema } from '@/types';

export const locationSchema: TemplateSchema = {
  id: 'location',
  name: 'Locations',
  description: 'Physical locations, sites, buildings and facilities across your organisation.',
  group: 'Location',
  icon: 'Building2',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'location id', 'site id', 'location code', 'site code', 'facility code', 'code', 'loc id'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the location',
      validation: { maxLength: 200, minLength: 1 },
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'location name', 'site name', 'facility name', 'building name', 'premises', 'site', 'location'],
      type: 'text',
      required: false,
      description: 'Display name for the location',
      transform: 'titleCase',
      validation: { maxLength: 200 },
    },
    {
      name: '% Owned',
      aliases: ['percent owned', 'ownership', 'ownership %', 'pct owned', 'owned percentage', '% ownership'],
      type: 'number',
      required: true,
      description: 'Percentage of location owned by the organisation',
      validation: { min: 0, max: 100 },
    },
    {
      name: 'Address (optional)',
      aliases: ['address', 'street address', 'street', 'address line 1', 'addr'],
      type: 'text',
      required: false,
      description: 'Street address of the location',
      validation: { maxLength: 300 },
    },
    {
      name: 'City (optional)',
      aliases: ['city', 'suburb', 'town', 'locality'],
      type: 'text',
      required: false,
      description: 'City or suburb',
      transform: 'titleCase',
    },
    {
      name: 'State (optional)',
      aliases: ['state', 'state/territory', 'territory', 'province', 'region'],
      type: 'text',
      required: false,
      description: 'State or territory',
    },
    {
      name: 'Postcode (optional)',
      aliases: ['postcode', 'post code', 'zip', 'zip code', 'postal code'],
      type: 'text',
      required: false,
      description: 'Postal or zip code',
      validation: { maxLength: 10 },
    },
    {
      name: 'Country (optional)',
      aliases: ['country', 'nation', 'country name'],
      type: 'text',
      required: false,
      description: 'Country where the location resides',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories', 'tag'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags for categorisation',
    },
  ],
  uniqueConstraint: ['Identifier'],
};
