import type { TemplateSchema } from '@/types';

export const scope2SourceSchema: TemplateSchema = {
  id: 'scope2-source',
  name: 'Scope 2 - Electricity Meters',
  description: 'Electricity meters for Scope 2 purchased electricity emissions tracking.',
  group: 'Scope 2 Emissions',
  icon: 'PlugZap',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'meter id', 'nmi', 'meter number', 'meter code', 'electricity meter'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the electricity meter',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'meter name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the meter',
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id', 'facility'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Supply Address (optional)',
      aliases: ['address', 'supply address', 'meter address', 'service address'],
      type: 'text',
      required: false,
      description: 'Supply address for the meter',
    },
    {
      name: 'Emission Factor',
      aliases: ['ef', 'emission factor', 'grid', 'state', 'grid region'],
      type: 'enum',
      required: true,
      description: 'Emission factor region for the meter',
      allowedValues: ['NSW', 'ACT', 'VIC', 'QLD', 'SA', 'WASWIS', 'WANWIS', 'TAS', 'NT', 'National'],
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date', 'connected date'],
      type: 'date',
      required: true,
      description: 'Date the meter became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date', 'disconnected date'],
      type: 'date',
      required: false,
      description: 'Date the meter became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const scope2QtySchema: TemplateSchema = {
  id: 'scope2-qty',
  name: 'Scope 2 - Quantities',
  description: 'Electricity consumption quantity data for Scope 2 reporting periods.',
  group: 'Scope 2 Emissions',
  icon: 'PlugZap',
  columns: [
    {
      name: 'Electricity Meter Identifier',
      aliases: ['meter id', 'identifier', 'nmi', 'meter', 'source id'],
      type: 'text',
      required: true,
      description: 'Identifier of the electricity meter',
    },
    {
      name: 'Total Quantity',
      aliases: ['quantity', 'qty', 'total', 'consumption', 'usage', 'kwh', 'amount'],
      type: 'number',
      required: true,
      description: 'Total electricity consumed',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (e.g. kWh, MWh)',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date', 'billing start'],
      type: 'date',
      required: true,
      description: 'Start of the billing/reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end', 'billing end'],
      type: 'date',
      required: false,
      description: 'End of the billing/reporting period',
    },
    {
      name: 'Tenant Identifier (optional)',
      aliases: ['tenant', 'tenant id', 'tenant code'],
      type: 'text',
      required: false,
      description: 'Identifier of the tenant (if sub-metered)',
    },
    {
      name: 'Tenant Quantity (optional)',
      aliases: ['tenant qty', 'tenant consumption', 'tenant usage', 'sub-metered'],
      type: 'number',
      required: false,
      description: 'Quantity attributable to the tenant',
    },
  ],
};

export const scope2TenantSchema: TemplateSchema = {
  id: 'scope2-tenant',
  name: 'Scope 2 - Tenants',
  description: 'Tenants associated with electricity meters for sub-metering.',
  group: 'Scope 2 Emissions',
  icon: 'PlugZap',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'tenant id', 'tenant code'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the tenant',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'tenant name', 'company name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the tenant',
    },
    {
      name: 'Supply Address (optional)',
      aliases: ['address', 'supply address', 'tenant address'],
      type: 'text',
      required: false,
      description: 'Supply address for the tenant',
    },
    {
      name: 'Electricity Meter Identifier',
      aliases: ['meter id', 'meter', 'nmi', 'meter identifier'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated electricity meter',
    },
  ],
  uniqueConstraint: ['Identifier'],
};
