import type { TemplateSchema } from '@/types';

export const scope3SourceSchema: TemplateSchema = {
  id: 'scope3-source',
  name: 'Scope 3 - Sources',
  description: 'Scope 3 value chain emission sources with category, calculation method and emission factors.',
  group: 'Scope 3 Emissions',
  icon: 'Globe',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'source code'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the Scope 3 source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the source',
    },
    {
      name: 'Supplier Identifier (optional)',
      aliases: ['supplier', 'supplier id', 'vendor', 'vendor id'],
      type: 'text',
      required: false,
      description: 'Identifier of the associated supplier',
    },
    {
      name: 'Scope 3 Category',
      aliases: ['category', 'scope3 category', 'ghg category', 'emission category'],
      type: 'enum',
      required: true,
      description: 'Scope 3 GHG Protocol category',
      allowedValues: [
        'Category 1 - purchased goods and services',
        'Category 2 - capital goods',
        'Category 3 - fuel and energy related activities',
        'Category 4 - upstream transport and distribution',
        'Category 5 - waste generated in operations',
        'Category 6 - business travel',
        'Category 7 - employee commuting',
        'Category 8 - upstream leased assets',
        'Category 9 - downstream transport and distribution',
        'Category 10 - processing of sold products',
        'Category 11 - use of sold products',
        'Category 12 - end of life treatment of sold products',
        'Category 13 - downstream leased assets',
        'Category 14 - franchises',
        'Category 15 - investments',
      ],
    },
    {
      name: 'Data Type',
      aliases: ['data source', 'data quality', 'primary secondary'],
      type: 'enum',
      required: true,
      description: 'Whether data is primary or secondary',
      allowedValues: ['Primary', 'Secondary'],
    },
    {
      name: 'Calculation Method',
      aliases: ['method', 'calc method', 'methodology'],
      type: 'enum',
      required: true,
      description: 'Emission calculation methodology',
      allowedValues: [
        'Supplier specific', 'Hybrid', 'Average data', 'Spend based',
        'Fuel based', 'Distance based', 'Site specific', 'Waste type specific',
        'Asset specific', 'Lesser lessee specific', 'Franchise specific', 'Investment specific',
      ],
    },
    {
      name: 'Activity Unit Type',
      aliases: ['unit type', 'activity type', 'measurement type'],
      type: 'enum',
      required: true,
      description: 'Type of activity unit',
      allowedValues: [
        'Energy', 'Mass', 'Volume', 'Length', 'Area', 'Emissions',
        'Currency', 'Time', 'Freight transport distance', 'Passenger transport distance', 'Quantity',
      ],
    },
    {
      name: 'Emission Factor Activity Id',
      aliases: ['ef id', 'emission factor id', 'activity id', 'ef activity id'],
      type: 'text',
      required: true,
      description: 'Emission factor activity identifier',
    },
    {
      name: 'Emission Factor Scope',
      aliases: ['ef scope', 'factor scope'],
      type: 'text',
      required: true,
      description: 'Scope of the emission factor (e.g. Scope 3 BP, Scope 3 PP)',
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date'],
      type: 'date',
      required: true,
      description: 'Date the source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date'],
      type: 'date',
      required: false,
      description: 'Date the source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const scope3QtySchema: TemplateSchema = {
  id: 'scope3-qty',
  name: 'Scope 3 - Quantities',
  description: 'Scope 3 emission quantity data for reporting periods.',
  group: 'Scope 3 Emissions',
  icon: 'Globe',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'source identifier', 'source code'],
      type: 'text',
      required: true,
      description: 'Identifier of the Scope 3 source',
    },
    {
      name: 'Quantity',
      aliases: ['qty', 'amount', 'value', 'activity data'],
      type: 'number',
      required: true,
      description: 'Activity quantity',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date'],
      type: 'date',
      required: true,
      description: 'Start of the reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end'],
      type: 'date',
      required: false,
      description: 'End of the reporting period',
    },
  ],
};

export const scope3SupplierSchema: TemplateSchema = {
  id: 'scope3-supplier',
  name: 'Scope 3 - Suppliers',
  description: 'Supplier master data for Scope 3 value chain emission tracking.',
  group: 'Scope 3 Emissions',
  icon: 'Globe',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'supplier id', 'vendor id', 'supplier code', 'vendor code'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the supplier',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'supplier name', 'vendor name', 'company name'],
      type: 'text',
      required: false,
      description: 'Display name for the supplier',
    },
    {
      name: 'Description (optional)',
      aliases: ['description', 'notes', 'details', 'comments'],
      type: 'text',
      required: false,
      description: 'Description of the supplier',
    },
  ],
  uniqueConstraint: ['Identifier'],
};
