import type { TemplateSchema } from '@/types';

export const wasteSourceSchema: TemplateSchema = {
  id: 'waste-source',
  name: 'Waste - Sources',
  description: 'Waste streams tracked for waste management and emission reporting.',
  group: 'Waste',
  icon: 'Trash2',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'waste id', 'stream id', 'waste stream id'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the waste source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'waste name', 'stream name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the waste source',
    },
    {
      name: 'Waste Category',
      aliases: ['category', 'waste type', 'waste category', 'sector'],
      type: 'enum',
      required: true,
      description: 'Category of waste',
      allowedValues: ['Residential', 'Commercial', 'Industrial'],
    },
    {
      name: 'Hazard Category',
      aliases: ['hazard', 'hazard type', 'hazardous', 'hazard class'],
      type: 'enum',
      required: true,
      description: 'Hazard classification',
      allowedValues: ['Non-Hazardous', 'Hazardous', 'Radioactive'],
    },
    {
      name: 'Disposal Method',
      aliases: ['disposal', 'method', 'treatment', 'disposal type'],
      type: 'enum',
      required: true,
      description: 'Waste disposal method',
      allowedValues: ['Composting', 'Incineration', 'Landfilling', 'Recycling', 'Repair', 'Reuse', 'Treatment', 'Other'],
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id', 'facility'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date'],
      type: 'date',
      required: true,
      description: 'Date the waste source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date'],
      type: 'date',
      required: false,
      description: 'Date the waste source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
    {
      name: 'Emission Factor Activity Id (optional)',
      aliases: ['ef id', 'emission factor id', 'ef activity id'],
      type: 'text',
      required: false,
      description: 'Emission factor activity identifier',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const wasteQtySchema: TemplateSchema = {
  id: 'waste-qty',
  name: 'Waste - Quantities',
  description: 'Waste quantity data for reporting periods.',
  group: 'Waste',
  icon: 'Trash2',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'waste source id', 'stream id'],
      type: 'text',
      required: true,
      description: 'Identifier of the waste source',
    },
    {
      name: 'Quantity',
      aliases: ['qty', 'amount', 'value', 'weight', 'volume', 'tonnage'],
      type: 'number',
      required: true,
      description: 'Waste quantity',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (e.g. kg, tonnes, m3)',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date'],
      type: 'date',
      required: true,
      description: 'Start of the reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end'],
      type: 'date',
      required: false,
      description: 'End of the reporting period',
    },
  ],
};
