import type { TemplateSchema } from '@/types';

export const waterSourceSchema: TemplateSchema = {
  id: 'water-source',
  name: 'Water - Sources',
  description: 'Water withdrawal and discharge sources for water stewardship reporting.',
  group: 'Water',
  icon: 'Droplets',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'water id', 'meter id'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the water source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'water name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the water source',
    },
    {
      name: 'Method',
      aliases: ['method', 'type', 'water method', 'withdrawal discharge'],
      type: 'enum',
      required: true,
      description: 'Whether water is withdrawn or discharged',
      allowedValues: ['Withdrawal', 'Discharge'],
    },
    {
      name: 'Water Type',
      aliases: ['water type', 'source type', 'water source type'],
      type: 'enum',
      required: true,
      description: 'Type of water source',
      allowedValues: [
        'Surface Water', 'Ground Water', 'Produced Water', 'Rain Water',
        'Sea Water', 'Third Party Potable Water', 'Third Party Non-Potable Water',
      ],
    },
    {
      name: 'Water Quality',
      aliases: ['quality', 'water quality', 'freshwater'],
      type: 'enum',
      required: true,
      description: 'Quality classification of the water',
      allowedValues: ['Freshwater', 'Other water'],
    },
    {
      name: 'Water Stress Level (optional)',
      aliases: ['stress', 'water stress', 'stress level', 'wri'],
      type: 'enum',
      required: false,
      description: 'Water stress level of the area',
      allowedValues: ['None', 'Low', 'Medium', 'High'],
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id', 'facility'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date'],
      type: 'date',
      required: true,
      description: 'Date the water source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date'],
      type: 'date',
      required: false,
      description: 'Date the water source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const waterQtySchema: TemplateSchema = {
  id: 'water-qty',
  name: 'Water - Quantities',
  description: 'Water consumption quantity data for reporting periods.',
  group: 'Water',
  icon: 'Droplets',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'water source id', 'meter id'],
      type: 'text',
      required: true,
      description: 'Identifier of the water source',
    },
    {
      name: 'Quantity',
      aliases: ['qty', 'amount', 'value', 'volume', 'consumption', 'usage'],
      type: 'number',
      required: true,
      description: 'Water quantity',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (e.g. kL, ML, m3)',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date'],
      type: 'date',
      required: true,
      description: 'Start of the reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end'],
      type: 'date',
      required: false,
      description: 'End of the reporting period',
    },
  ],
};
