import type { TemplateSchema } from '@/types';

export const whsSourceSchema: TemplateSchema = {
  id: 'whs-source',
  name: 'WHS - Sources',
  description: 'Work health and safety metric sources for injury, incident and hours tracking.',
  group: 'WHS',
  icon: 'ShieldAlert',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'whs id', 'metric id'],
      type: 'text',
      required: true,
      description: 'Unique identifier for the WHS source',
    },
    {
      name: 'Name (optional)',
      aliases: ['name', 'source name', 'metric name', 'description'],
      type: 'text',
      required: false,
      description: 'Display name for the WHS source',
    },
    {
      name: 'Metric Group',
      aliases: ['group', 'metric group', 'category', 'metric category'],
      type: 'enum',
      required: true,
      description: 'WHS metric group',
      allowedValues: [
        'Worked Hours',
        'Identification and Assessment',
        'WHS Management',
        'Injury and Incident Recording',
      ],
    },
    {
      name: 'Metric Type',
      aliases: ['type', 'metric type', 'metric', 'kpi'],
      type: 'enum',
      required: true,
      description: 'Specific WHS metric type',
      allowedValues: [
        'Hours Worked',
        'WHS Interactions',
        'Hazards Reported',
        'Near Misses Reported',
        'HiPos Reported',
        'Injuries or Incident Investigations Conducted',
        'Hazards Mitigated Or Resolved',
        'Near Misses Investigated And Actioned',
        'HiPos With Implemented Controls',
        'Fatalities',
        'Lost Time Injuries',
        'Medical Treatment Injuries',
        'Permanent Disability Injuries',
        'First Aid Injuries',
        'Environment and Community Incidents',
        'Community Grievances Lodged',
        'Plant or Property Incidents',
        'ESG Incidents',
      ],
    },
    {
      name: 'Person Type',
      aliases: ['person', 'worker type', 'employment type', 'person category'],
      type: 'enum',
      required: true,
      description: 'Type of worker',
      allowedValues: ['Employees', 'Contractors', 'Subcontractors'],
    },
    {
      name: 'Location Identifier',
      aliases: ['location', 'location id', 'site', 'site id', 'facility'],
      type: 'text',
      required: true,
      description: 'Identifier of the associated location',
    },
    {
      name: 'Active Date',
      aliases: ['start date', 'active from', 'from date'],
      type: 'date',
      required: true,
      description: 'Date the WHS source became active',
    },
    {
      name: 'Inactive Date (optional)',
      aliases: ['end date', 'inactive from', 'to date'],
      type: 'date',
      required: false,
      description: 'Date the WHS source became inactive',
    },
    {
      name: 'Tags (optional)',
      aliases: ['tags', 'labels', 'categories'],
      type: 'text',
      required: false,
      description: 'Comma-separated tags',
    },
  ],
  uniqueConstraint: ['Identifier'],
};

export const whsQtySchema: TemplateSchema = {
  id: 'whs-qty',
  name: 'WHS - Quantities',
  description: 'WHS metric quantity data for reporting periods.',
  group: 'WHS',
  icon: 'ShieldAlert',
  columns: [
    {
      name: 'Identifier',
      aliases: ['id', 'source id', 'whs source id', 'metric id'],
      type: 'text',
      required: true,
      description: 'Identifier of the WHS source',
    },
    {
      name: 'Quantity',
      aliases: ['qty', 'amount', 'value', 'count', 'hours'],
      type: 'number',
      required: true,
      description: 'WHS metric quantity',
    },
    {
      name: 'Unit',
      aliases: ['uom', 'unit of measure', 'measurement unit'],
      type: 'text',
      required: true,
      description: 'Unit of measurement (hr/hrs/hours or qty)',
    },
    {
      name: 'Start Date',
      aliases: ['start', 'from date', 'period start', 'begin date'],
      type: 'date',
      required: true,
      description: 'Start of the reporting period',
    },
    {
      name: 'End Date (optional)',
      aliases: ['end', 'to date', 'period end'],
      type: 'date',
      required: false,
      description: 'End of the reporting period',
    },
  ],
};
